describe('Teste de compras EBAC', () => {
  it('Fluxo de compra', () => {
    cy.visit('https://www.saucedemo.com/')                           
    cy.get('[data-test="username"]').type('standard_user')          
    cy.get('[data-test="password"]').type('secret_sauce')            
    cy.get('[data-test="login-button"]').click()                     
    cy.get('[data-test="title"]').should('contain', "Products")      
    cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').click()                          
    cy.get('[data-test="remove-sauce-labs-bike-light"]').should('contain', "Remove")          
    cy.get('[data-test="shopping-cart-badge"]').should('contain', "1")                        
    cy.get('[data-test="shopping-cart-link"]').click()                                       
    cy.get('[data-test="title"]').should('contain', "Your Cart")                           
    cy.get('[data-test="checkout"]').click()                                               
    cy.get('[data-test="firstName"]').type('Usuário')                                     
    cy.get('[data-test="lastName"]').type('Standard')                                    
    cy.get('[data-test="postalCode"]').type('00000-000')                                
    cy.get('[data-test="continue"]').click()                                          
    cy.get('[data-test="total-info-label"]').should('contain', "Total")               
    cy.get('[data-test="finish"]').click()                                          
    cy.get('[data-test="complete-header"]').should('contain', "Thank")             
  })
})
